### ISSUE TITLE
CA appended to bundle but `openssl verify` fails

### ISSUE THREAD

**Issue by neoice** [evenup/evenup-trusted_ca#15]
https://github.com/evenup/evenup-trusted_ca/blob/master/manifests/ca.pp#L62

I'm not sure *why* `openssl verify` fails, but I thought the impact was humorous: the CA will be appended every time Puppet runs. this could potentially exhaust your disk space if you let it run long enough. when I discovered it, my broken CA was appended to the CA bundle about 40 times :)

is there room for some kind of "CA validation" before the append occurs?

**Comment by jlambert121** [comment]
Closing this with the version 1.0 rework.  It no longer appends certificates and does things "the right way".
